GET http://localhost:3003/api/users

###
GET http://localhost:3003/api/users/64ecf580077a96ea8cf5c1bb

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "testium",
  "name": "Test Dummy",
  "password": "testword123456"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "another",
  "name": "Test Dummy",
  "password": "testword123456"
}