###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Blog 2",
  "author": "Rizvan",
  "url": "test-url",
  "likes": 0,
  "userId":"64e3b5967181169a161b223a"
}

###
GET http://localhost:3003/api/non-existant