###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTNiNjI5NzE4MTE2OWExNjFiMjIzYyIsInVzZXJuYW1lIjoiYW5vdGhlciIsImlhdCI6MTY5MjczNjAwOSwiZXhwIjoxNjkyNzM5NjA5fQ._Bbq9LFkf-r0mD3krv7DZKEfSzvybbZYbOAZ2VDqWvA

{
  "title": "Test Blog 5",
  "url": "test-url",
  "likes": 0
}

###
GET http://localhost:3003/api/non-existant

###
DELETE http://localhost:3003/api/blogs/64e51a58eb9c294e62f54b02
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTNiNjI5NzE4MTE2OWExNjFiMjIzYyIsInVzZXJuYW1lIjoiYW5vdGhlciIsImlhdCI6MTY5MjczNjAwOSwiZXhwIjoxNjkyNzM5NjA5fQ._Bbq9LFkf-r0mD3krv7DZKEfSzvybbZYbOAZ2VDqWvA