###
GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/:id

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Blog",
  "author": "Test Dummy",
  "url": "test-url",
  "likes": 9999
}